### ISSUE TITLE
Empty graph visualization

### ISSUE THREAD

**Issue by rrooij** [terminusdb/terminusdb-console#1]
# Problem

Schemaless get-only queries don't display a schema

# Version

terminusdb-quickstart master, terminusdb-server 2.0.2 and terminusdb-console 2.0.3.

# How to reproduce

1. Run terminusdb-quickstart on the master branch and run `./terminusdb-container run`
2. Go to the address
3. Create a new empty database
4. Enter the following query in the query pane and press "Execute query"

```
WOQL.get(
    WOQL.as("Start station","v:Start_Station")
        .as("End station", "v:End_Station")
        .as("Start date", "v:Start_Time")
        .as("End date", "v:End_Time")
        .as("Duration", "v:Duration")
        .as("Start station number", "v:Start_ID")
        .as("End station number", "v:End_ID")
        .as("Bike number", "v:Bike")
        .as("Member type", "v:Member_Type")
).remote("https://terminusdb.com/t/data/bike_tutorial.csv")
```

5. Click Graph in the dropdown instead of table
6. A white screen appears instead of a graph

# Expected results

Either it should display some kind of warning that no graph could be produced because the data has no relations, has no defined structure etc. or it should be displayed.

**Comment by kevinchekovfeeney** [comment]
Fixed in v2.0.4 - and in terminusdb-react-graph v0.0.4
