### ISSUE TITLE
Cannot connect to Terminus Hub on self-hosted console

### ISSUE THREAD

**Issue by kaaloo** [terminusdb/terminusdb-console#15]
**Describe the bug**
Redirect url restrictions in `auth0` breaks the authentication flow when connecting to Terminus Hub.

**To Reproduce**

Prerequisites:

- a self-hosted `terminusdb` instance accessible via HTTPS on a specific URL, e.g., https://terminusdb.mydomain.dev

1. Go to the instance URL and enter the admin password
2. Click on the green Connect to Hub link in the navbar
3. See error

**Expected behavior**
The `auth0` signup / login screen should allow registering our logging in to Terminus Hub.

**Screenshots**
Connect to hub on self hosted `terminusdb` instance.
![image](https://user-images.githubusercontent.com/67010/111959379-ae891100-8aee-11eb-94a5-806c1195eaea.png)

auth0 error message

![image](https://user-images.githubusercontent.com/67010/111959455-c496d180-8aee-11eb-87a0-f3c066d0f578.png)

**Info (please complete the following information):**
 - Kubernetes 1.20.4 using `terminusdb/terminusdb-server:v4.2.0` docker image

**Additional context**
It might be worthwhile hiding the Terminus Hub features in the console if the console is not  on an authorized callback URL.  Since `terminusdb` could potentially be hosted anywhere, it seems that a different auth flow would be required, perhaps by always reaching auth0 from a `terminusdb.com` endpoint like `accounts.terminusdb.com` although I'm not quite sure if there are any security issues.

**Comment by Cheukting** [comment]
@luke-feeney @Francesca-Bit @rrooij @GavinMendelGleason will talk about it and hopefully provide an answer.

**Comment by rrooij** [comment]
Thanks for the suggestion! While your suggestion is indeed a better way, for now, supporting this pattern is not on our roadmap.
