### ISSUE TITLE
Searching for Publisher in Console

### ISSUE THREAD

**Issue by luke-feeney** [terminusdb/terminusdb-console#4]
**Describe the bug**
When I try to search for a `publisher ` in the console the `publisher` is case sensitive but there is no warning screen when i search for the specific publisher (`Gavin` vs `gavin`) with the wrong case 

**To Reproduce**
Go to console and type in a publisher name with the wrong case - you will get no results if the cases are not used correctly

**Expected behavior**
I expected either 1) a warning saying that it is case sensitive, or 2) the box not to allow me to enter a capitalised name

**Screenshots**
NA

**Info (please complete the following information):**
- OS: Windows Electron App
- How did you run terminus-server: electron 

**Additional context**
Cheuk found this bug during the DBPedia hackathon

**Comment by luke-feeney** [comment]
![image](https://user-images.githubusercontent.com/53231019/94011479-53749c80-fd9f-11ea-8cbb-428a51d712b1.png)

![image](https://user-images.githubusercontent.com/53231019/94011517-65563f80-fd9f-11ea-8c03-e08d2d65e020.png)

**Comment by GavinMendelGleason** [comment]
No longer going to be fixed.
