### ISSUE TITLE
The infinity sign is bleeding across on the merge and branch screen

### ISSUE THREAD

**Issue by luke-feeney** [terminusdb/terminusdb-console#5]
This is in the electron app on windows on the merge screen when it is in the non full-screen mode, the infinity sign bleeds into the 'Merge Branches' text. Screenshot for reference. (not a major bug, but worth mentioning)

![image](https://user-images.githubusercontent.com/53231019/95493911-0db9f580-0995-11eb-9604-139ac00c0bcf.png)

**Comment by Francesca-Bit** [comment]
Fixed image size
