### ISSUE TITLE
"commit generated with javascript client without message"

### ISSUE THREAD

**Issue by dwinston** [terminusdb/terminusdb-console#7]
When I follow the steps of <https://terminusdb.com/docs/tutorials/branch-tutorial/> and create the new schema
```
WOQL.doctype("BankAccount").label("Bank Account")
    .property("owner","xsd:string")
       .label("owner")
       .cardinality(1)
    .property("balance","xsd:nonNegativeInteger")
       .label("balance")
       .cardinality(1)
```
, I enter "New Schema" as instructed in the 'Enter reason for update here'-placeholder commit message input, but I get a commit message of "Commit generated with javascript client without message" in the Latest Updates section of the DB Home view. I was using Firefox 84.0.1 on macOS Catalina 10.15.7, and I am running terminusdb-bootstrap via cloning <https://github.com/terminusdb/terminusdb-bootstrap> and running `./terminusdb-container run` from the latest commit (3abb4ec).

All of my commit messages similarly have this default value for previous tutorials, where I also tried to enter in commit messages as above. Please advise.

**Comment by KittyJose** [comment]
Hello dwinston, 
Thanks very much for spotting out this bug. We have resolved this and the fix will be available soon after some sanity tests 👍

**Comment by KittyJose** [comment]
Fix released in dev/canary
