### ISSUE TITLE
not able to merge branch in console

### ISSUE THREAD

**Issue by dwinston** [terminusdb/terminusdb-console#8]
I successfully got to the "rebase" section of https://terminusdb.com/docs/tutorials/branch-tutorial/ and was able to add the information as specified to each branch (I'm running `TERMINUSDB_TAG=canary ./terminusdb-container run` to benefit from the fix of #7, which works -- thank you!).

However, when I go to "Manage" in the menu, click on the "main" branch, click on the "Merge to branch" icon, select "branch_office" so that I see "Merge from branch branch_office to main" displayed, enter a commit log message, and click "Merge into main branch", I do get a "Successfully merged branch_office into branch main (0.094 seconds)" message, but my commit does not appear in the "Latest Updates on main branch" table, and I don't see doc:jim in the Documents view.

The UI in the canary console is different than that in the tutorial, but I think I'm following the intended path. Please advise. Is this a bug, or am I just not doing it correctly?

**Comment by dwinston** [comment]
Also, I *think* my db with both branches is synced to terminushub as `dwinston/banker2`, if that helps with troubleshooting.

**Comment by luke-feeney** [comment]
Was 100% sure that I had seen this issue pop-up and then I lost it. Happy to have rediscovered. Will take a look and will discuss at out documentation and issue triage in the discord server at 2pm tomorrow (every thursday). Feel free to join - but I'll also report back.

**Comment by luke-feeney** [comment]
I was able to recreate and it is a bug in canary - @KittyJose is working on it now. Fix will be pushed soon and will certainly appear in next main release.

**Comment by luke-feeney** [comment]
Hello @dwinston! We solved the issue (well @KittyJose & @Francesca-Bit ) did. Fixed in canary and soon to be pushed out in the next major release.

Good point on the changing UI! Hard for the tutorials to keep up if i'm being honest. Documentation debt is real.

**Comment by dwinston** [comment]
Thank you!
