### ISSUE TITLE
Console dies on query

### ISSUE THREAD

**Issue by GavinMendelGleason** [terminusdb/terminusdb-console#9]
Load the DBPedia data set, and attempt the following query:

```javascript
limit(1)
  .path("doc:Queen_(band)", "scm:bandMember+", "v:member", "v:path")
```

This leads to an error:

```javascript
ReferenceError: prefixes is not defined
```
Similarly on the Seshat data set: 

```javascript
using("admin/seshat/local/commit/54dhg6h4hfq8jxk5h03tlmlmbbua9oe").read_object("terminusdb:///data/afghazn", "v:Doc")
```

![prefix error](https://user-images.githubusercontent.com/1993386/107850764-28015580-6e05-11eb-9c8d-a3b39607d9c3.png)

**Comment by Francesca-Bit** [comment]
fixed, error in result rendering
